default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: stock_development
  username: emmanuelkamala
  password: Tanzania99!!
  port: 5433
  
test:
  <<: *default
  database: stock_test
  username: emmanuelkamala
  password: Tanzania99!!
  port: 5433

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: stock_production
  username: stock
  password: <%= ENV["STOCK_DATABASE_PASSWORD"] %>
